---
- name: Centralized Security Scan Collection
  hosts: Test1
  become: yes
  vars:
    collector_log_dir: /home/mduroot/security_scan_collector
    scan_script_path: /usr/local/bin/security_scan.sh
    client_log_path: /tmp/security_scan.log

  tasks:

    # Step 1: Deploy the script to client
    - name: Deploy security_scan.sh script to client
      copy:
        dest: "{{ scan_script_path }}"
        mode: '0755'
        content: |
          #!/bin/bash
          LOGFILE="{{ client_log_path }}"
          echo "===== Security Scan: $(date) =====" > $LOGFILE
          OS_FAMILY=$(awk -F= '/^ID=/{print $2}' /etc/os-release | tr -d '"')
          ...
          # (rest of the script remains unchanged)

    # Step 2: Execute the script on the client
    - name: Execute security scan on client
      shell: "{{ scan_script_path }}"
      register: scan_result

    - name: Debug client scan execution
      debug:
        var: scan_result

    # Step 3: Fetch the log from the client to control node
    - name: Fetch scan output from client
      fetch:
        src: "{{ client_log_path }}"
        dest: "{{ collector_log_dir }}/security_scan_{{ inventory_hostname }}.log"
        flat: yes

    # Step 4: Cleanup temporary log on client
    - name: Remove temp log on client
      file:
        path: "{{ client_log_path }}"
        state: absent
