---
- name: Centralized Security Scan Collection
  hosts: 172.17.9.59
  become: yes
  vars:
    collector_log_dir: /var/log/security_scan_collector

  tasks:

    # ---------------------------
    # Step 1: Create the security scan script on client
    # ---------------------------
    - name: Deploy security_scan.sh script to client
      copy:
        dest: /usr/local/bin/security_scan.sh
        mode: '0755'
        content: |
          #!/bin/bash
          LOGFILE="/tmp/security_scan.log"
          echo "===== Security Scan: $(date) =====" > $LOGFILE

          # 1. Missing OS Security Updates
          echo "[MISSING_OS_UPDATES]" >> $LOGFILE
          apt list --upgradable 2>/dev/null | grep -i security >> $LOGFILE || echo "No security updates"

          # 2. Outdated Packages
          echo "[OUTDATED_PACKAGES]" >> $LOGFILE
          apt list --upgradable 2>/dev/null >> $LOGFILE || echo "No outdated packages"

          # 3. Kernel Vulnerabilities
          echo "[KERNEL]" >> $LOGFILE
          uname -r >> $LOGFILE
          apt list --upgradable 2>/dev/null | grep linux-image >> $LOGFILE || echo "No kernel updates"

          # 4. Vulnerable Versions of Apps
          echo "[VULNERABLE_APPS]" >> $LOGFILE
          dpkg -l | egrep "apache2|nginx|mysql|php" >> $LOGFILE || echo "No vulnerable apps found"

          # 5. Weak Security Settings
          echo "[WEAK_SETTINGS]" >> $LOGFILE
          grep -i "minlen" /etc/security/pwquality.conf || echo "minlen not set"

    # ---------------------------
    # Step 2: Run the security scan on client
    # ---------------------------
    - name: Execute security scan on client
      shell: /usr/local/bin/security_scan.sh
      register: scan_output
      ignore_errors: yes

    # ---------------------------
    # Step 3: Ensure collector directory exists on Ansible control node
    # ---------------------------
    - name: Ensure collector log directory exists on control node
      local_action:
        module: file
        path: "{{ collector_log_dir }}"
        state: directory
        mode: '0755'

    # ---------------------------
    # Step 4: Copy scan output to collector
    # ---------------------------
    - name: Copy client scan output to collector node
      fetch:
        src: /tmp/security_scan.log
        dest: "{{ collector_log_dir }}/security_scan_{{ inventory_hostname }}.log"
        flat: yes

    # ---------------------------
    # Optional Step 5: Clean up temp log on client
    # ---------------------------
    - name: Remove temp log on client
      file:
        path: /tmp/security_scan.log
        state: absent
